// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFbsvRLylDRjkGNqdf3QTAh-eKqLXnkzs',
    appId: '1:124531075016:web:2e082001f33f62d7bcc2fd',
    messagingSenderId: '124531075016',
    projectId: 'property-pulse-d764a',
    authDomain: 'property-pulse-d764a.firebaseapp.com',
    storageBucket: 'property-pulse-d764a.firebasestorage.app',
    measurementId: 'G-06TRJSFN4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS3_iPTThAyYN_7VRlqsM99JI27TgLwhA',
    appId: '1:124531075016:android:b590683e4ff59d9fbcc2fd',
    messagingSenderId: '124531075016',
    projectId: 'property-pulse-d764a',
    storageBucket: 'property-pulse-d764a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8FQeh8FJfA0woVqlvaa6SETmxO0W9nqQ',
    appId: '1:124531075016:ios:5d491f5536a94f78bcc2fd',
    messagingSenderId: '124531075016',
    projectId: 'property-pulse-d764a',
    storageBucket: 'property-pulse-d764a.firebasestorage.app',
    iosBundleId: 'com.example.propertyPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8FQeh8FJfA0woVqlvaa6SETmxO0W9nqQ',
    appId: '1:124531075016:ios:5d491f5536a94f78bcc2fd',
    messagingSenderId: '124531075016',
    projectId: 'property-pulse-d764a',
    storageBucket: 'property-pulse-d764a.firebasestorage.app',
    iosBundleId: 'com.example.propertyPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFbsvRLylDRjkGNqdf3QTAh-eKqLXnkzs',
    appId: '1:124531075016:web:88afc8b3409782fabcc2fd',
    messagingSenderId: '124531075016',
    projectId: 'property-pulse-d764a',
    authDomain: 'property-pulse-d764a.firebaseapp.com',
    storageBucket: 'property-pulse-d764a.firebasestorage.app',
    measurementId: 'G-MM9PQY9NGL',
  );
}
